var jrjActList = ['adminUser','promo','adminFish'];
var jrjActOpt = {'admin':true};
var jrjCfgAdminUser = {name:'adminUser','host':'admin','keyField':'id',label:'Inactive User',labelPlural:'Inactive Users','key':'id','displayField':'username',
		   'fields': [
{'type':'text','name':'username','label':'Username','listShow':true,'shortShow':true,'mapShow':true,'readOnEdit':false,'tipNew':'Length > 2. Alphanumeric or (- . _)','required':true,'tipEdit':'Changing your Username will break external links to your old Username'},
{'type':'row','fields':[
			{'type':'password','label':'Password','name':'password','editShow':false,'newShow':true,'readShow':false,'required':true},
			{'type':'password','label':'Password Verify','name':'password_verify','editShow':false,'newShow':true,'readShow':false,'required':true}
			]},
{'type':'row','fields':[
{'type':'text','name':'email','label':'Email','listShow':false,'shortShow':false,'required':true},
{'type':'text','name':'title','label':'title'}
			]},
{'type':'row','fields':[
{'type':'text','name':'firstname','label':'First','listShow':true,'shortShow':true,'mapShow':true},
{'type':'text','name':'lastname','label':'Last','listShow':true,'shortShow':true,'mapShow':true}
			]},
{'type':'row','fields':[
{'type':'text','name':'location','label':'Location','listShow':true,'shortShow':true,'searchShow':false,'searchType':'contain'},
{'type':'text','name':'website','label':'Website'}
			]},
{'type':'row','fields':[
			{'type':'select','name':'utype','label':'User Type','newShow':true,'editShow':true,'selectLabel':'utypeLabel','selectValue':'utypeValue'},
{'type':'text','name':'utype_text','label':'User Type','searchShow':false,'editShow':false,'newShow':false},
			{'type':'text','name':'date_create','label':'Join Date','newShow':false,'readOnEdit':true}
			]},
{'type':'row','fields':[
{'type':'text','name':'company','label':'Company','listShow':false,'shortShow':true,'mapShow':true},
{'type':'text','name':'phone','label':'Phone','listShow':false,'shortShow':true,'mapShow':true}
			]},
{'type':'textarea','name':'about','mapShow':false,'label':'About'},
{'type':'textarea','name':'feed','mapShow':false,'editShow':false,'newShow':false,'readShow':false},
{'type':'hidden','name':'lat'},
{'type':'hidden','name':'lon'},
{'type':'hidden','name':'id'},
{'type':'hidden','name':'admin','defaultValue':10}
],
		       'recordList':[],
		       'recordHash':{},
		       ajaxUrlBB: '/admin/a/aUsersBB',
		       ajaxUrlById: '/admin/a/aGetUser',
		       ajaxUrlEdit: '/admin/a/aUserEdit',
		   ajaxUrlEditGeo: '/admin/a/aUserEditGeo',
		   ajaxUrlSearch: '/admin/a/aUserSearch',
   	           ajaxUrlNew: '/admin/a/aUserNew',
		       urlUpload:'/admin/a/upload',
		   iconUrlSmall: '/images/map/user16.png',
		   iconUrlMed: '/images/map/user16.png',
		   iconUrlMedSz: [16,24,0,0,8,12],
		   utypeLabel:['Recreational Fishing','Pro Fishing','Fishing Guide','Charter Fishing'],
		   utypeValue:[1,5,15,20],
		   titleField: 'date_create',
		   allowMapButtons:true,
		   allowEdit: true,
		   allowNew:true,
		       allowList:true,
		      allowDelete: true,
			   allowActionBar:true,
			   children:['promoSentUser']
		       };

var jrjCfgPromo = {name:'promo','host':'admin','keyField':'id',label:'Promotion',labelPlural:'Promotions','displayField':'caption',
		  'fields': [ 
{'type':'text','name':'caption','label':'Caption','required':true,'listShow':true,'shortShow':true,'searchShow':true,'searchType':'start','mapShow':true},
{'type':'text','name':'email_from','label':'Email From','required':true,'mapShow':false},
{'type':'text','name':'name_from','label':'Name From','required':false,'mapShow':false},
{'type':'text','name':'title_from','label':'Title From','required':false,'mapShow':false},
{'type':'text','name':'subject','label':'Subject','required':true,'mapShow':true},
{'type':'text','name':'date_create','label':'Date','required':false,'readShow':true,'mapShow':true,'newShow':false,'editShow':false},
{'type':'button','name':'mapEdit','buttonLabel':'Change Location on Map','readShow':false,'clickSub':'mapEdit','newShow':false},
{'type':'hidden','name':'lat','label':'Lat'},
{'type':'hidden','name':'lon','label':'Lon'},
{'type':'hidden','name':'id'},
{'type':'hidden','name':'user_id'},
			      ],
		   'recordList':[],
		   'recordHash':{},
		      allowEdit: true,
		      allowDelete: true,
		      allowPhotos: false,
		      allowReply: false,
		      allowFish: false,
		       allowGeo:true,
		       allowHeadLink:false,
		  ajaxUrlBB: '/admin/a/aPromoBB',
		  ajaxUrlById: '/admin/a/aPromoGet',
		  ajaxUrlNew: '/admin/a/aPromoNew',
		  ajaxUrlEdit: '/admin/a/aPromoEdit',
		   ajaxUrlEditGeo: '/admin/a/aPromoEditGeo',
		  ajaxUrlDelete: '/admin/a/aPromoDelete',
		  ajaxUrlSearch: '/admin/a/aPromoSearch',
		  iconUrlSmall: '/images/map/spotSmall.png',
		  iconUrlSmallBg: '/images/map/spotSmallShadow.png',
		  iconUrlSmallSz: [10,16,0,0,5,8],
		  iconUrlMed: '/images/map/spotMed.png',
		  iconUrlMedSz: [15,24,0,0,7,12],
		  iconUrlMedBgSz: [28,24,0,0,14,12],
		   titleField: 'date_create',
			   children:['promoSent']
};

var jrjCfgPromoSent = {name:'promoSent','host':'admin','keyField':'id',label:'Promo Sent',labelPlural:'Promos Sent','displayField':'date_create',
		  'fields': [ 
{'type':'text','name':'date_create','label':'Date','required':false,'readShow':true,'mapShow':true,'newShow':false},
{'type':'text','name':'promo_username','label':'Promo User','newShow':false},
{'type':'text','name':'caption','label':'Promo','newShow':false},
{'type':'text','name':'email_from','label':'Email From','newShow':false},
{'type':'text','name':'status_text','label':'Status','newShow':false,'editShow':false},
{'type':'hidden','name':'id'},
{'type':'hidden','name':'pid','label':'Promotion','XeditSub':'promoEditSelect','required':true},
{'type':'hidden','name':'promo_user_id','label':'Promo User'},
{'type':'hidden','name':'user_id','label':'User'},
			      ],
		   'recordList':[],
		   'recordHash':{},
		      allowEdit: true,
		      allowDelete: true,
		      allowPhotos: false,
		      allowReply: false,
		      allowFish: false,
		       allowGeo:false,
		       allowHeadLink:false,
		       allowActionBar:false,
		  ajaxUrlBB: '/admin/a/aPromoSentBB',
		  ajaxUrlGetAll: '/admin/a/aPromoSentByParent',
		  ajaxUrlById: '/admin/a/aPromoSentGet',
		  ajaxUrlNew: '/admin/a/aPromoSentNew',
		  ajaxUrlEdit: '/admin/a/aPromoSentEdit',
		  ajaxUrlDelete: '/admin/a/aPromoSentDelete',
		  ajaxUrlSearch: '/admin/a/aPromoSentSearch',
		  iconUrlSmall: '/images/map/spotSmall.png',
		  iconUrlSmallBg: '/images/map/spotSmallShadow.png',
		  iconUrlSmallSz: [10,16,0,0,5,8],
		  iconUrlMed: '/images/map/spotMed.png',
		  iconUrlMedSz: [15,24,0,0,7,12],
		  iconUrlMedBgSz: [28,24,0,0,14,12],
		  titleField: 'date_create'
};

var jrjCfgPromoSentUser = {name:'promoSentUser','host':'admin','keyField':'id',label:'User Promo',labelPlural:'User Promos','displayField':'date_create',
		  'fields': [ 
{'type':'text','name':'date_create','label':'Date','required':false,'readShow':true,'mapShow':true,'newShow':false},
{'type':'text','name':'promo_username','label':'Promo User','newShow':false},
{'type':'text','name':'caption','label':'Promo','newShow':false},
{'type':'text','name':'email_from','label':'Email From','newShow':false},
{'type':'text','name':'status_text','label':'Status','newShow':false,'editShow':false},
{'type':'button','name':'process','buttonLabel':'Preview/Send','readShow':true,'clickSub':'promoProcessInit','newShow':false,'editShow':false},
{'type':'hidden','name':'id'},
{'type':'hidden','name':'pid','label':'Promotion','editSub':'promoEditSelect','required':true},
{'type':'hidden','name':'promo_user_id','label':'Promo User'},
{'type':'hidden','name':'user_id','label':'User'},
			      ],
		   'recordList':[],
		   'recordHash':{},
		      allowEdit: true,
		      allowDelete: true,
		      allowPhotos: false,
		      allowReply: false,
		      allowFish: false,
		       allowGeo:false,
		       allowHeadLink:false,
		       allowActionBar:false,
		  ajaxUrlBB: '/admin/a/aPromoSentBB',
		  ajaxUrlGetAll: '/admin/a/aPromoSentByUser',
		  ajaxUrlById: '/admin/a/aPromoSentGet',
		  ajaxUrlNew: '/admin/a/aPromoSentNew',
		  ajaxUrlEdit: '/admin/a/aPromoSentEdit',
		  ajaxUrlDelete: '/admin/a/aPromoSentDelete',
		  ajaxUrlSearch: '/admin/a/aPromoSentSearch',
		  iconUrlSmall: '/images/map/spotSmall.png',
		  iconUrlSmallBg: '/images/map/spotSmallShadow.png',
		  iconUrlSmallSz: [10,16,0,0,5,8],
		  iconUrlMed: '/images/map/spotMed.png',
		  iconUrlMedSz: [15,24,0,0,7,12],
		  iconUrlMedBgSz: [28,24,0,0,14,12],
		  titleField: 'date_create'
};

var jrjCfgAdminFish = {'name':'adminFish','keyField':'id','label':'Fish','labelPlural':'Fish','displayField':'name',
		  'fields': [
{'type':'text','name':'name','label':'Name','required':true,'listShow':true,'tip':'Name of Fish','shortShow':true,'searchShow':true,'searchType':'contain','mapShow':true},
{'type':'text','name':'name_sci','label':'Scientific','required':false,'tip':'Scientific name if you know it','shortShow':true,'mapShow':true,'searchShow':false,'searchType':'contain'},
{'type':'textarea','name':'alias','label':'Aliases','searchShow':true,'searchType':'contain','tip':'Other names for this Fish'},
{'type':'textarea','name':'detail','label':'Detail','searchShow':false,'searchType':'contain','tip':'Required. Maximum 500 characters'},
{'type':'button','name':'mapEdit','buttonLabel':'Change Location on Map','readShow':false,'clickSub':'mapEdit','newShow':false},
{'type':'hidden','name':'id'},
{'type':'hidden','name':'lat'},
{'type':'hidden','name':'lon'}
			      ],
		  'recordList':[],
		  'recordHash':{},
		  allowEdit: true,
		  allowDelete: true,
		  allowPhotos: false,
		  allowReply: false,
	          allowGeo:true,
		      allowFish: false,
		      allowSearchBounds:true,
		  allowActionBar:true,
		  allowHead:true,
		  allowHeadLink:false,
		  ajaxUrlBB: '/fish/a/aGetBB',
		  ajaxUrlById: '/fish/a/aGet',
		  ajaxUrlNew: '/fish/a/aNew',
		  ajaxUrlEdit: '/fish/a/aEdit',
		  ajaxUrlDelete: '/fish/a/aDelete',
		  ajaxUrlEditGeo: '/fish/a/aEditGeo',
		  ajaxUrlSearch: '/fish/a/aSearch',
		  urlUpload:'/fish/upload',
		  iconUrlSmall: '/images/map/fish16.png',
		  iconUrlSmallSz: [16,16,0,0,5,8],
		  iconUrlMed: '/images/map/fish24.png',
		  iconUrlMedSz: [24,24,0,0,7,12],
		  titleField: 'name'
};
